[2025-09-16T16:40:34.159+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline_postgres_debug.transform __airflow_temporary_run_2025-09-16T16:35:26.278388+00:00__ [queued]>
[2025-09-16T16:40:34.164+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline_postgres_debug.transform __airflow_temporary_run_2025-09-16T16:35:26.278388+00:00__ [queued]>
[2025-09-16T16:40:34.164+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-09-16T16:40:34.172+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform> on 2025-09-16 00:00:00+00:00
[2025-09-16T16:40:34.177+0000] {standard_task_runner.py:57} INFO - Started process 118 to run task
[2025-09-16T16:40:34.179+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline_postgres_debug', 'transform', '__***_temporary_run_2025-09-16T16:35:26.278388+00:00__', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/coleta_dados.py', '--cfg-path', '/tmp/tmpaucu97ri']
[2025-09-16T16:40:34.180+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask transform
[2025-09-16T16:40:34.211+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_pipeline_postgres_debug.transform __airflow_temporary_run_2025-09-16T16:35:26.278388+00:00__ [running]> on host c990452d66b1
[2025-09-16T16:40:34.258+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline_postgres_debug' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2025-09-16T16:35:26.278388+00:00__'
[2025-09-16T16:40:34.259+0000] {logging_mixin.py:151} INFO - === TRANSFORMAÇÃO ===
[2025-09-16T16:40:34.268+0000] {logging_mixin.py:151} INFO - Dados antes da transformação:
[2025-09-16T16:40:34.291+0000] {logging_mixin.py:151} INFO -          id  ...              last_updated
0   bitcoin  ...  2025-09-16T16:35:00.905Z
1  ethereum  ...  2025-09-16T16:35:00.941Z
2   cardano  ...  2025-09-16T16:34:54.639Z

[3 rows x 26 columns]
[2025-09-16T16:40:34.292+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'last_updated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coleta_dados.py", line 57, in transformar_dados
    df['last_updated'] = df['last_updated'].astype(str)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'last_updated'
[2025-09-16T16:40:34.300+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=crypto_pipeline_postgres_debug, task_id=transform, execution_date=20250916T000000, start_date=20250916T164034, end_date=20250916T164034
[2025-09-16T16:40:34.307+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task transform ('last_updated'; 118)
[2025-09-16T16:40:34.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-16T16:40:34.367+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
